feat: step-guide
defi-wonderland/xERC20 pull request #2
Opened 2023-10-27 21:00 UTC by prathmeshkhandelwal1

- Added steps guide for deploying `xERC20` and `Lockbox`.

2023-10-30 08:14 UTC, 0xShaito requested changes

2023-10-30 08:14 UTC, 0xShaito commented on README.md
> +> :information*source: Notice: \_Please ensure that all private keys (PKs) are prefixed with `0x` before using or submitting them. This prefix is necessary for proper formatting and compatibility.*
ty :pray:

2023-10-30 08:14 UTC, 0xShaito commented on example.md
> +This guide provides a detailed, step-by-step process to deploy an xERC20 token using this repository. We will first demonstrate how to deploy the xERC20 token alone, and then we’ll cover the scenario
We will not be covering the other case right? The deploy with lockbox I mean

2023-10-30 08:14 UTC, 0xShaito commented on example.md
> +## Setup Guide to Deploy an xERC20 Token
A part of this is written in the README. Can we merge it with that and consolidate in there so it shows when you open the repo?

Also I think it's a good idea to move the section now to the top of the README as it's in the bottom now!

2023-10-30 15:03 UTC, 0xShaito approved these changes

2023-10-31 12:59 UTC, rhlsthrm approved these changes

2023-10-31 19:07 UTC, 0xGorilla approved these changes

2023-11-14 15:06 UTC, 0xGorilla requested changes
Please pull and push. All of the broadcast changes were already merged in another PR

2023-11-14 18:26 UTC, 0xGorilla approved these changes

2023-11-14 18:26 UTC, merged