fix: use ERC20Permit and update constructor
defi-wonderland/xERC20 pull request #5
Opened 2023-11-13 03:44 UTC by SvenMeyer

Since @openzeppelin/contracts v4.9 is only redirecting to the now final ERC20Permit implementatation.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.9/contracts/token/ERC20/extensions/draft-ERC20Permit.sol

Since @openzeppelin contracts v5.0 `draft-ERC20Permit.sol` has been removed.

2023-11-14 11:21 UTC, 0xShaito commented
Linked issues:

https://github.com/defi-wonderland/xERC20/issues/3

https://github.com/defi-wonderland/xERC20/issues/4

2023-11-14 12:20 UTC, 0xShaito commented
Hi @SvenMeyer. PR looks great and it's a good idea! For it to be ready we need:

1) The version of openzeppelin should be updated in the `.gitmodules`:

(we can safely remove the other part [submodule "lib\\openzeppelin-contracts"])

```
[submodule "lib/openzeppelin-contracts"]
	path = lib/openzeppelin-contracts
	url = https://github.com/OpenZeppelin/openzeppelin-contracts
	branch = merge/release-v5.0
```

2) This will require a change in the version of the compiler in `foundry.toml` and in the contracts (replace all):

```
[profile.default]
solc = '0.8.23'
```

3) Some small tests will fail like the one that checks the symbol!

After that the pr should be fully ready and we will merge it as soon as we try it :) 

ty!

2023-11-14 15:40 UTC, 0xShaito requested changes
Hi @SvenMeyer. PR looks great and it's a good idea! For it to be ready we need:

1) The version of openzeppelin should be updated in the `.gitmodules`:

(we can safely remove the other part [submodule "lib\\openzeppelin-contracts"])

```
[submodule "lib/openzeppelin-contracts"]
	path = lib/openzeppelin-contracts
	url = https://github.com/OpenZeppelin/openzeppelin-contracts
	branch = merge/release-v5.0
```

2) This will require a change in the version of the compiler in `foundry.toml` and in the contracts (replace all):

```
[profile.default]
solc = '0.8.23'
```

3) Some small tests will fail like the one that checks the symbol!

After that the pr should be fully ready and we will merge it as soon as we try it :) 

ty!

2023-12-03 10:55 UTC, SvenMeyer commented
@0xShaito Sorry for the delay .. wanted to get it working first
- reverted to `OpenZeppelin/openzeppelin-contracts@release-v4.9` to not intruduce any beaking changes at this stage
- fixed tests to not expect token name and symbol to start with 'x' (after deployment, token name and symbol will be as specified = unchanged)
- cloned into a fresh repo, all tests working
Please review

2023-12-04 11:02 UTC, excaliborr approved these changes
lgtm!

2023-12-07 09:02 UTC, SvenMeyer commented
@0xShaito @excaliborr @prathmeshkhandelwal1 Anything left to do from my side ?

2023-12-08 11:18 UTC, 0xGorilla submitted a review, later dismissed

2023-12-11 21:56 UTC, 0xGorilla commented
@SvenMeyer I did replicate your changes on PR #7 since I needed to also deploy everything to 10 chains and target the dev branch.

Ty for your contribution!

2023-12-11 21:56 UTC, closed without merging